"""Add emotion and voice profile id

Revision ID: 99a81756ea78
Revises: 143991594047
Create Date: 2026-02-27 15:55:38.449211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a81756ea78'
down_revision: Union[str, Sequence[str], None] = '143991594047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scriptsegment', sa.Column('emotion', sa.String(), nullable=True))
    op.add_column('scriptsegment', sa.Column('voice_profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'scriptsegment', 'voiceprofile', ['voice_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scriptsegment', type_='foreignkey')
    op.drop_column('scriptsegment', 'voice_profile_id')
    op.drop_column('scriptsegment', 'emotion')
    # ### end Alembic commands ###
